### ISSUE TITLE
Page "flashes" when first loading

### ISSUE THREAD

**Issue by cjerdonek** [teorth/QED#11]
If you load the page, you'll notice that a bunch of content "flashes" before going away.

I'm guessing this is because the content starts out displayed, and then the JS hides it when first executing. It would be better if it starts out hidden to prevent the flashing.

**Comment by teorth** [comment]
I think I fixed this, though I'm not sure the solution is the most elegant - the exercise text window (which has the intro text, and is the main source of flashing because the text is cleared if localstorage is nonempty ) is now set to a hidden CSS style initiallly, and the className is changed once the text is finalised.
