### ISSUE TITLE
Reset single exercise

### ISSUE THREAD

**Issue by Voileexperiments** [teorth/QED#30]
It seems that the only to reset an exercise (due exercise content changes) is to either modify the local storage manually, or restart *the whole game*. It'd be good to have a button to just reset the selected exercise.

**Comment by teorth** [comment]
There already is a "restart exercise" button (and a hotkey "r"), but do you mean something else?  It is true that due to changes in an exercise (e.g. 1.1) one can artificially have a proof of an exercise that is shorter than the record.  I guess I could add an "unsolve" button to remove the solved status (and proof) of a given exercise, is this what you have in mind?

**Comment by Voileexperiments** [comment]
> an "unsolve" button to remove the solved status (and proof) of a given exercise

Yes.

**Comment by teorth** [comment]
This is now implemented.
